# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'app.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QStackedWidget, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1022, 779)
        palette = QPalette()
        brush = QBrush(QColor(121, 131, 145, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush)
        MainWindow.setPalette(palette)
        icon = QIcon()
        icon.addFile(u"Images/Logo/MainLogo.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QSize(30, 30))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, 0, 1021, 751))
        self.page_1 = QWidget()
        self.page_1.setObjectName(u"page_1")
        self.label_2 = QLabel(self.page_1)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(450, 0, 161, 61))
        palette1 = QPalette()
        brush1 = QBrush(QColor(255, 255, 255, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush1)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        brush2 = QBrush(QColor(255, 255, 255, 128))
        brush2.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush2)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush2)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush2)
#endif
        self.label_2.setPalette(palette1)
        font = QFont()
        font.setFamilies([u"Eras Demi ITC"])
        font.setPointSize(26)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_2.setScaledContents(True)
        self.line = QFrame(self.page_1)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 360, 1024, 20))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.label_7 = QLabel(self.page_1)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(80, 330, 311, 41))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush1)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush2)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush2)
#endif
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush2)
#endif
        self.label_7.setPalette(palette2)
        font1 = QFont()
        font1.setFamilies([u"Eras Demi ITC"])
        font1.setPointSize(16)
        self.label_7.setFont(font1)
        self.label_7.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_7.setScaledContents(True)
        self.label_8 = QLabel(self.page_1)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(320, 20, 401, 321))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush1)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Active, QPalette.PlaceholderText, brush2)
#endif
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush2)
#endif
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush2)
#endif
        self.label_8.setPalette(palette3)
        font2 = QFont()
        font2.setFamilies([u"Eras Demi ITC"])
        font2.setPointSize(36)
        self.label_8.setFont(font2)
        self.label_8.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_8.setTextFormat(Qt.PlainText)
        self.label_8.setPixmap(QPixmap(u"Images/Logo/GesturePlayLogo_yello.png"))
        self.label_8.setScaledContents(True)
        self.label_3 = QLabel(self.page_1)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(510, 60, 41, 61))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette4.setBrush(QPalette.Active, QPalette.Text, brush1)
        palette4.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Active, QPalette.PlaceholderText, brush2)
#endif
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.Text, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush2)
#endif
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.Text, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.ButtonText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush2)
#endif
        self.label_3.setPalette(palette4)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(u"\n"
"color: rgb(255, 255, 255);")
        self.label_3.setScaledContents(True)
        self.Profile1 = QPushButton(self.page_1)
        self.Profile1.setObjectName(u"Profile1")
        self.Profile1.setGeometry(QRect(420, 440, 211, 71))
        self.Profile1.setCursor(QCursor(Qt.OpenHandCursor))
        self.Profile1.setStyleSheet(u"QPushButton{\n"
"      color: rgb(255, 255, 255);\n"
"      border:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"      background-color: rgba(236, 236, 236, 30);\n"
"}")
        icon1 = QIcon()
        icon1.addFile(u"Images/Icons/MainStartButton.png", QSize(), QIcon.Normal, QIcon.Off)
        self.Profile1.setIcon(icon1)
        self.Profile1.setIconSize(QSize(300, 150))
        self.label_9 = QLabel(self.page_1)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(-2, -5, 1031, 751))
        self.label_9.setStyleSheet(u"background-color: rgb(64, 70, 77);")
        self.label_9.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.stackedWidget.addWidget(self.page_1)
        self.label_9.raise_()
        self.label_2.raise_()
        self.line.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_3.raise_()
        self.Profile1.raise_()
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.logoutBtn = QPushButton(self.page_2)
        self.logoutBtn.setObjectName(u"logoutBtn")
        self.logoutBtn.setGeometry(QRect(10, 660, 191, 81))
        font3 = QFont()
        font3.setFamilies([u"Eras Bold ITC"])
        font3.setPointSize(12)
        self.logoutBtn.setFont(font3)
        self.logoutBtn.setCursor(QCursor(Qt.PointingHandCursor))
        self.logoutBtn.setLayoutDirection(Qt.LeftToRight)
        self.logoutBtn.setStyleSheet(u"QPushButton{\n"
"      color: rgb(255, 255, 255);\n"
"      border:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"      background-color: rgb(153, 178, 208);\n"
"}")
        icon2 = QIcon()
        icon2.addFile(u"Images/Icons/Logouticon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.logoutBtn.setIcon(icon2)
        self.logoutBtn.setIconSize(QSize(50, 55))
        self.cameraSettingsBtn = QPushButton(self.page_2)
        self.cameraSettingsBtn.setObjectName(u"cameraSettingsBtn")
        self.cameraSettingsBtn.setGeometry(QRect(0, 150, 231, 71))
        self.cameraSettingsBtn.setFont(font3)
        self.cameraSettingsBtn.setCursor(QCursor(Qt.PointingHandCursor))
        self.cameraSettingsBtn.setLayoutDirection(Qt.LeftToRight)
        self.cameraSettingsBtn.setStyleSheet(u"QPushButton{\n"
"      color: rgb(255, 255, 255);\n"
"      border:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"      background-color: rgb(153, 178, 208);\n"
"}")
        icon3 = QIcon()
        icon3.addFile(u"Images/Icons/camera-setting-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.cameraSettingsBtn.setIcon(icon3)
        self.cameraSettingsBtn.setIconSize(QSize(50, 55))
        self.controlsSettingsBtn = QPushButton(self.page_2)
        self.controlsSettingsBtn.setObjectName(u"controlsSettingsBtn")
        self.controlsSettingsBtn.setGeometry(QRect(0, 71, 231, 71))
        self.controlsSettingsBtn.setFont(font3)
        self.controlsSettingsBtn.setCursor(QCursor(Qt.PointingHandCursor))
        self.controlsSettingsBtn.setStyleSheet(u"QPushButton{\n"
"      color: rgb(255, 255, 255);\n"
"      border:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"      background-color: rgb(153, 178, 208);\n"
"}")
        icon4 = QIcon()
        icon4.addFile(u"Images/Icons/controllerSettingsIcon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.controlsSettingsBtn.setIcon(icon4)
        self.controlsSettingsBtn.setIconSize(QSize(50, 50))
        self.gameSelectionBtn = QPushButton(self.page_2)
        self.gameSelectionBtn.setObjectName(u"gameSelectionBtn")
        self.gameSelectionBtn.setGeometry(QRect(0, 0, 231, 71))
        self.gameSelectionBtn.setFont(font3)
        self.gameSelectionBtn.setCursor(QCursor(Qt.PointingHandCursor))
        self.gameSelectionBtn.setStyleSheet(u"background-color: rgb(99, 122, 155);\n"
"color: rgb(255, 255, 255);\n"
"border:none;")
        icon5 = QIcon()
        icon5.addFile(u"Images/Icons/ControllerIcon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.gameSelectionBtn.setIcon(icon5)
        self.gameSelectionBtn.setIconSize(QSize(80, 80))
        self.label = QLabel(self.page_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 0, 231, 751))
        self.label.setPixmap(QPixmap(u"Images/Backdrops/SidePanel.png"))
        self.label.setScaledContents(True)
        self.stackedWidget_2 = QStackedWidget(self.page_2)
        self.stackedWidget_2.setObjectName(u"stackedWidget_2")
        self.stackedWidget_2.setGeometry(QRect(229, -1, 791, 771))
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.label_38 = QLabel(self.page_3)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(0, 0, 841, 111))
        self.label_38.setPixmap(QPixmap(u"Images/Backdrops/HeaderBackGround.png"))
        self.label_38.setScaledContents(True)
        self.label_39 = QLabel(self.page_3)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(20, 20, 251, 51))
        font4 = QFont()
        font4.setFamilies([u"Eras Bold ITC"])
        font4.setPointSize(22)
        self.label_39.setFont(font4)
        self.label_39.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_40 = QLabel(self.page_3)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(20, 50, 251, 51))
        font5 = QFont()
        font5.setFamilies([u"Eras Demi ITC"])
        font5.setPointSize(14)
        self.label_40.setFont(font5)
        self.label_40.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_41 = QLabel(self.page_3)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(60, 310, 101, 51))
        font6 = QFont()
        font6.setFamilies([u"Eras Demi ITC"])
        font6.setPointSize(11)
        self.label_41.setFont(font6)
        self.label_41.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.lightSpeedBtn = QPushButton(self.page_3)
        self.lightSpeedBtn.setObjectName(u"lightSpeedBtn")
        self.lightSpeedBtn.setGeometry(QRect(50, 200, 111, 121))
        self.lightSpeedBtn.setFont(font3)
        self.lightSpeedBtn.setCursor(QCursor(Qt.PointingHandCursor))
        self.lightSpeedBtn.setLayoutDirection(Qt.LeftToRight)
        self.lightSpeedBtn.setStyleSheet(u"QPushButton{\n"
"      background-color: none;\n"
"      border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"      background-color: rgba(255, 255, 255, 30);\n"
"}")
        icon6 = QIcon()
        icon6.addFile(u"Images/Icons/trachmaniaIcon.jpg", QSize(), QIcon.Normal, QIcon.Off)
        self.lightSpeedBtn.setIcon(icon6)
        self.lightSpeedBtn.setIconSize(QSize(150, 150))
        self.lineEdit_2 = QLineEdit(self.page_3)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(50, 140, 441, 31))
        font7 = QFont()
        font7.setFamilies([u"Eras Demi ITC"])
        font7.setPointSize(12)
        self.lineEdit_2.setFont(font7)
        self.lineEdit_2.setLayoutDirection(Qt.RightToLeft)
        self.lineEdit_2.setStyleSheet(u"background-color: rgb(121, 131, 145);\n"
"border-color: #ffffff;\n"
"color: rgb(255, 255, 255);")
        self.label_48 = QLabel(self.page_3)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(220, 310, 101, 51))
        self.label_48.setFont(font6)
        self.label_48.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.tankGameBtn = QPushButton(self.page_3)
        self.tankGameBtn.setObjectName(u"tankGameBtn")
        self.tankGameBtn.setGeometry(QRect(210, 200, 111, 121))
        self.tankGameBtn.setFont(font3)
        self.tankGameBtn.setCursor(QCursor(Qt.PointingHandCursor))
        self.tankGameBtn.setLayoutDirection(Qt.LeftToRight)
        self.tankGameBtn.setStyleSheet(u"QPushButton{\n"
"      background-color: none;\n"
"      border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"      background-color: rgba(255, 255, 255, 30);\n"
"}")
        self.tankGameBtn.setIcon(icon6)
        self.tankGameBtn.setIconSize(QSize(150, 150))
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.label_42 = QLabel(self.page_4)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(20, 30, 251, 51))
        self.label_42.setFont(font4)
        self.label_42.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.Profile1_3 = QPushButton(self.page_4)
        self.Profile1_3.setObjectName(u"Profile1_3")
        self.Profile1_3.setGeometry(QRect(50, 150, 151, 131))
        self.Profile1_3.setCursor(QCursor(Qt.ArrowCursor))
        self.Profile1_3.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        icon7 = QIcon()
        icon7.addFile(u"Images/1x/Profile1.png", QSize(), QIcon.Normal, QIcon.Off)
        self.Profile1_3.setIcon(icon7)
        self.Profile1_3.setIconSize(QSize(100, 100))
        self.label_44 = QLabel(self.page_4)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(200, 220, 251, 51))
        font8 = QFont()
        font8.setFamilies([u"Eras Demi ITC"])
        font8.setPointSize(18)
        self.label_44.setFont(font8)
        self.label_44.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.editProfileBtn_2 = QPushButton(self.page_4)
        self.editProfileBtn_2.setObjectName(u"editProfileBtn_2")
        self.editProfileBtn_2.setGeometry(QRect(290, 220, 21, 21))
        self.editProfileBtn_2.setCursor(QCursor(Qt.PointingHandCursor))
        self.editProfileBtn_2.setStyleSheet(u"QPushButton{\n"
"      background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"      background-color: rgb(160, 173, 191);\n"
"}")
        icon8 = QIcon()
        icon8.addFile(u"Images/Icons/editicon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.editProfileBtn_2.setIcon(icon8)
        self.editProfileBtn_2.setIconSize(QSize(25, 25))
        self.label_45 = QLabel(self.page_4)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(0, 0, 801, 111))
        self.label_45.setPixmap(QPixmap(u"Images/Backdrops/HeaderBackGround.png"))
        self.label_45.setScaledContents(True)
        self.stackedWidget_2.addWidget(self.page_4)
        self.Profile1_3.raise_()
        self.label_44.raise_()
        self.editProfileBtn_2.raise_()
        self.label_45.raise_()
        self.label_42.raise_()
        self.page_5 = QWidget()
        self.page_5.setObjectName(u"page_5")
        self.removeProfileBtn_4 = QPushButton(self.page_5)
        self.removeProfileBtn_4.setObjectName(u"removeProfileBtn_4")
        self.removeProfileBtn_4.setGeometry(QRect(320, 580, 131, 50))
        font9 = QFont()
        font9.setFamilies([u"Eras Bold ITC"])
        self.removeProfileBtn_4.setFont(font9)
        self.removeProfileBtn_4.setCursor(QCursor(Qt.PointingHandCursor))
        self.removeProfileBtn_4.setStyleSheet(u"QPushButton {\n"
"    border-radius: 25px;\n"
"\n"
"      color: rgb(255, 255, 255);\n"
"\n"
"      background-color: rgb(122, 147, 183);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"      background-color: rgb(145, 176, 218);\n"
"}")
        self.label_25 = QLabel(self.page_5)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(30, 130, 251, 51))
        font10 = QFont()
        font10.setFamilies([u"Eras Bold ITC"])
        font10.setPointSize(18)
        self.label_25.setFont(font10)
        self.label_25.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_43 = QLabel(self.page_5)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(20, 30, 251, 51))
        self.label_43.setFont(font4)
        self.label_43.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.CameraSelection = QComboBox(self.page_5)
        self.CameraSelection.setObjectName(u"CameraSelection")
        self.CameraSelection.setGeometry(QRect(30, 200, 431, 31))
        self.CameraSelection.setFont(font7)
        self.CameraSelection.setStyleSheet(u"background-color: rgb(144, 155, 172);\n"
"color: rgb(255, 255, 255);")
        self.label_46 = QLabel(self.page_5)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(30, 152, 251, 51))
        self.label_46.setFont(font1)
        self.label_46.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_47 = QLabel(self.page_5)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(0, 0, 801, 111))
        self.label_47.setPixmap(QPixmap(u"Images/Backdrops/HeaderBackGround.png"))
        self.label_47.setScaledContents(True)
        self.CameraPreview = QLabel(self.page_5)
        self.CameraPreview.setObjectName(u"CameraPreview")
        self.CameraPreview.setGeometry(QRect(160, 300, 241, 161))
        self.stackedWidget_2.addWidget(self.page_5)
        self.label_47.raise_()
        self.removeProfileBtn_4.raise_()
        self.label_25.raise_()
        self.label_43.raise_()
        self.CameraSelection.raise_()
        self.label_46.raise_()
        self.CameraPreview.raise_()
        self.page_6 = QWidget()
        self.page_6.setObjectName(u"page_6")
        self.label_32 = QLabel(self.page_6)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(0, 0, 801, 111))
        self.label_32.setPixmap(QPixmap(u"Images/Backdrops/HeaderBackGround.png"))
        self.label_32.setScaledContents(True)
        self.label_50 = QLabel(self.page_6)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(20, 30, 251, 51))
        self.label_50.setFont(font4)
        self.label_50.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.Key_A = QLabel(self.page_6)
        self.Key_A.setObjectName(u"Key_A")
        self.Key_A.setGeometry(QRect(-70, 170, 300, 220))
        self.Key_A.setPixmap(QPixmap(u"Images/Icons/A.PNG"))
        self.Key_A.setScaledContents(True)
        self.Key_D = QLabel(self.page_6)
        self.Key_D.setObjectName(u"Key_D")
        self.Key_D.setGeometry(QRect(-70, 390, 300, 220))
        self.Key_D.setPixmap(QPixmap(u"Images/Icons/D.PNG"))
        self.Key_D.setScaledContents(True)
        self.Key_S = QLabel(self.page_6)
        self.Key_S.setObjectName(u"Key_S")
        self.Key_S.setGeometry(QRect(-70, 280, 300, 220))
        self.Key_S.setPixmap(QPixmap(u"Images/Icons/S.PNG"))
        self.Key_S.setScaledContents(True)
        self.Key_W = QLabel(self.page_6)
        self.Key_W.setObjectName(u"Key_W")
        self.Key_W.setGeometry(QRect(-70, 60, 300, 220))
        self.Key_W.setPixmap(QPixmap(u"Images/Icons/W.PNG"))
        self.Key_W.setScaledContents(True)
        self.imgLabel1 = QLabel(self.page_6)
        self.imgLabel1.setObjectName(u"imgLabel1")
        self.imgLabel1.setGeometry(QRect(100, 90, 200, 150))
        self.imgLabel1.setPixmap(QPixmap(u"Images/Icons/ThumbsUp.PNG"))
        self.imgLabel1.setScaledContents(True)
        self.imgLabel2 = QLabel(self.page_6)
        self.imgLabel2.setObjectName(u"imgLabel2")
        self.imgLabel2.setGeometry(QRect(100, 200, 200, 150))
        self.imgLabel2.setPixmap(QPixmap(u"Images/Icons/ThumbsDown.PNG"))
        self.imgLabel2.setScaledContents(True)
        self.imgLabel3 = QLabel(self.page_6)
        self.imgLabel3.setObjectName(u"imgLabel3")
        self.imgLabel3.setGeometry(QRect(110, 310, 200, 150))
        self.imgLabel3.setPixmap(QPixmap(u"Images/Icons/Fist.PNG"))
        self.imgLabel3.setScaledContents(True)
        self.imgLabel4 = QLabel(self.page_6)
        self.imgLabel4.setObjectName(u"imgLabel4")
        self.imgLabel4.setGeometry(QRect(100, 420, 200, 150))
        self.imgLabel4.setPixmap(QPixmap(u"Images/Icons/Flat.PNG"))
        self.imgLabel4.setScaledContents(True)
        self.Key_G = QLabel(self.page_6)
        self.Key_G.setObjectName(u"Key_G")
        self.Key_G.setGeometry(QRect(-70, 500, 300, 220))
        self.Key_G.setPixmap(QPixmap(u"Images/Icons/G.png"))
        self.Key_G.setScaledContents(True)
        self.imgLabel5 = QLabel(self.page_6)
        self.imgLabel5.setObjectName(u"imgLabel5")
        self.imgLabel5.setGeometry(QRect(100, 530, 200, 150))
        self.imgLabel5.setPixmap(QPixmap(u"Images/Icons/Gun.PNG"))
        self.imgLabel5.setScaledContents(True)
        self.Key_I = QLabel(self.page_6)
        self.Key_I.setObjectName(u"Key_I")
        self.Key_I.setGeometry(QRect(230, 60, 300, 220))
        self.Key_I.setPixmap(QPixmap(u"Images/Icons/I.png"))
        self.Key_I.setScaledContents(True)
        self.Key_O = QLabel(self.page_6)
        self.Key_O.setObjectName(u"Key_O")
        self.Key_O.setGeometry(QRect(230, 170, 300, 220))
        self.Key_O.setPixmap(QPixmap(u"Images/Icons/O.png"))
        self.Key_O.setScaledContents(True)
        self.Key_P = QLabel(self.page_6)
        self.Key_P.setObjectName(u"Key_P")
        self.Key_P.setGeometry(QRect(230, 280, 300, 220))
        self.Key_P.setPixmap(QPixmap(u"Images/Icons/P.png"))
        self.Key_P.setScaledContents(True)
        self.Key_U = QLabel(self.page_6)
        self.Key_U.setObjectName(u"Key_U")
        self.Key_U.setGeometry(QRect(230, 390, 300, 220))
        self.Key_U.setPixmap(QPixmap(u"Images/Icons/U.png"))
        self.Key_U.setScaledContents(True)
        self.imgLabel6 = QLabel(self.page_6)
        self.imgLabel6.setObjectName(u"imgLabel6")
        self.imgLabel6.setGeometry(QRect(400, 100, 200, 150))
        self.imgLabel6.setPixmap(QPixmap(u"Images/Icons/Inward.PNG"))
        self.imgLabel6.setScaledContents(True)
        self.imgLabel7 = QLabel(self.page_6)
        self.imgLabel7.setObjectName(u"imgLabel7")
        self.imgLabel7.setGeometry(QRect(400, 200, 200, 150))
        self.imgLabel7.setPixmap(QPixmap(u"Images/Icons/FacingAway.PNG"))
        self.imgLabel7.setScaledContents(True)
        self.imgLabel8 = QLabel(self.page_6)
        self.imgLabel8.setObjectName(u"imgLabel8")
        self.imgLabel8.setGeometry(QRect(400, 320, 200, 150))
        self.imgLabel8.setPixmap(QPixmap(u"Images/Icons/FacingTowards.PNG"))
        self.imgLabel8.setScaledContents(True)
        self.imgLabel9 = QLabel(self.page_6)
        self.imgLabel9.setObjectName(u"imgLabel9")
        self.imgLabel9.setGeometry(QRect(400, 420, 200, 150))
        self.imgLabel9.setPixmap(QPixmap(u"Images/Icons/Outward.PNG"))
        self.imgLabel9.setScaledContents(True)
        self.label_36 = QLabel(self.page_6)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(370, 560, 200, 150))
        self.label_36.setPixmap(QPixmap(u"Images/Icons/Click.PNG"))
        self.label_36.setScaledContents(True)
        self.label_37 = QLabel(self.page_6)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(280, 560, 200, 150))
        self.label_37.setPixmap(QPixmap(u"Images/Icons/LMB.png"))
        self.label_37.setScaledContents(True)
        self.label_49 = QLabel(self.page_6)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(490, 545, 200, 150))
        self.label_49.setPixmap(QPixmap(u"Images/Icons/MoveMouse.png"))
        self.label_49.setScaledContents(True)
        self.label_51 = QLabel(self.page_6)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(610, 550, 200, 150))
        self.label_51.setPixmap(QPixmap(u"Images/Icons/Cursor.PNG"))
        self.label_51.setScaledContents(True)
        self.stackedWidget_2.addWidget(self.page_6)
        self.Key_I.raise_()
        self.label_32.raise_()
        self.label_50.raise_()
        self.Key_A.raise_()
        self.Key_D.raise_()
        self.Key_S.raise_()
        self.Key_W.raise_()
        self.imgLabel1.raise_()
        self.imgLabel2.raise_()
        self.imgLabel3.raise_()
        self.imgLabel4.raise_()
        self.Key_G.raise_()
        self.imgLabel5.raise_()
        self.Key_O.raise_()
        self.Key_P.raise_()
        self.Key_U.raise_()
        self.imgLabel6.raise_()
        self.imgLabel7.raise_()
        self.imgLabel8.raise_()
        self.imgLabel9.raise_()
        self.label_36.raise_()
        self.label_37.raise_()
        self.label_49.raise_()
        self.label_51.raise_()
        self.stackedWidget.addWidget(self.page_2)
        self.label.raise_()
        self.logoutBtn.raise_()
        self.cameraSettingsBtn.raise_()
        self.controlsSettingsBtn.raise_()
        self.gameSelectionBtn.raise_()
        self.stackedWidget_2.raise_()
        self.page_9 = QWidget()
        self.page_9.setObjectName(u"page_9")
        self.label_20 = QLabel(self.page_9)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(260, 130, 131, 21))
        font11 = QFont()
        font11.setFamilies([u"Eras Bold ITC"])
        font11.setPointSize(16)
        self.label_20.setFont(font11)
        self.label_20.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_16 = QLabel(self.page_9)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(270, 180, 681, 41))
        font12 = QFont()
        font12.setFamilies([u"Eras Light ITC"])
        font12.setPointSize(12)
        self.label_16.setFont(font12)
        self.label_16.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_21 = QLabel(self.page_9)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(600, 360, 121, 51))
        self.label_21.setFont(font5)
        self.label_21.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_22 = QLabel(self.page_9)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(230, 0, 801, 111))
        self.label_22.setPixmap(QPixmap(u"Images/Backdrops/HeaderBackGround.png"))
        self.label_22.setScaledContents(True)
        self.label_23 = QLabel(self.page_9)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(90, 50, 131, 31))
        self.label_23.setFont(font11)
        self.label_23.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.logoutBtn_3 = QPushButton(self.page_9)
        self.logoutBtn_3.setObjectName(u"logoutBtn_3")
        self.logoutBtn_3.setGeometry(QRect(10, 660, 191, 51))
        self.logoutBtn_3.setFont(font3)
        self.logoutBtn_3.setCursor(QCursor(Qt.PointingHandCursor))
        self.logoutBtn_3.setLayoutDirection(Qt.LeftToRight)
        self.logoutBtn_3.setStyleSheet(u"QPushButton{\n"
"      color: rgb(255, 255, 255);\n"
"      border:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"      background-color: rgb(153, 178, 208);\n"
"}")
        self.logoutBtn_3.setIcon(icon2)
        self.logoutBtn_3.setIconSize(QSize(50, 55))
        self.launchGameBtn_2 = QPushButton(self.page_9)
        self.launchGameBtn_2.setObjectName(u"launchGameBtn_2")
        self.launchGameBtn_2.setGeometry(QRect(830, 40, 171, 50))
        font13 = QFont()
        font13.setFamilies([u"Eras Bold ITC"])
        font13.setPointSize(11)
        self.launchGameBtn_2.setFont(font13)
        self.launchGameBtn_2.setCursor(QCursor(Qt.PointingHandCursor))
        self.launchGameBtn_2.setStyleSheet(u"QPushButton {\n"
"    border-radius: 25px;\n"
"\n"
"      color: rgb(255, 255, 255);\n"
"\n"
"      background-color: rgb(122, 147, 183);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"      background-color: rgb(145, 176, 218);\n"
"}")
        icon9 = QIcon()
        icon9.addFile(u"Images/Icons/playButton.png", QSize(), QIcon.Normal, QIcon.Off)
        self.launchGameBtn_2.setIcon(icon9)
        self.launchGameBtn_2.setIconSize(QSize(50, 50))
        self.label_24 = QLabel(self.page_9)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(600, 290, 121, 51))
        self.label_24.setFont(font5)
        self.label_24.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.LightSpeedClip_2 = QLabel(self.page_9)
        self.LightSpeedClip_2.setObjectName(u"LightSpeedClip_2")
        self.LightSpeedClip_2.setGeometry(QRect(290, 460, 141, 101))
        self.LightSpeedClip_2.setScaledContents(True)
        self.label_26 = QLabel(self.page_9)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(310, 430, 121, 51))
        self.label_26.setFont(font5)
        self.label_26.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.Key_G_3 = QLabel(self.page_9)
        self.Key_G_3.setObjectName(u"Key_G_3")
        self.Key_G_3.setGeometry(QRect(620, 255, 161, 121))
        self.Key_G_3.setPixmap(QPixmap(u"Images/Icons/G.png"))
        self.Key_G_3.setScaledContents(True)
        self.Key_P_3 = QLabel(self.page_9)
        self.Key_P_3.setObjectName(u"Key_P_3")
        self.Key_P_3.setGeometry(QRect(617, 325, 171, 121))
        self.Key_P_3.setPixmap(QPixmap(u"Images/Icons/P.png"))
        self.Key_P_3.setScaledContents(True)
        self.label_27 = QLabel(self.page_9)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(260, 260, 131, 21))
        self.label_27.setFont(font11)
        self.label_27.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_28 = QLabel(self.page_9)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(0, 0, 231, 731))
        self.label_28.setPixmap(QPixmap(u"Images/Backdrops/SidePanel.png"))
        self.label_28.setScaledContents(True)
        self.Key_A_3 = QLabel(self.page_9)
        self.Key_A_3.setObjectName(u"Key_A_3")
        self.Key_A_3.setGeometry(QRect(387, 470, 151, 111))
        self.Key_A_3.setPixmap(QPixmap(u"Images/Icons/A.PNG"))
        self.Key_A_3.setScaledContents(True)
        self.controlsSettingsBtn_4 = QPushButton(self.page_9)
        self.controlsSettingsBtn_4.setObjectName(u"controlsSettingsBtn_4")
        self.controlsSettingsBtn_4.setGeometry(QRect(90, 80, 91, 31))
        font14 = QFont()
        font14.setFamilies([u"Eras Medium ITC"])
        font14.setPointSize(10)
        self.controlsSettingsBtn_4.setFont(font14)
        self.controlsSettingsBtn_4.setCursor(QCursor(Qt.PointingHandCursor))
        self.controlsSettingsBtn_4.setStyleSheet(u"QPushButton{\n"
"      color: rgb(255, 255, 255);\n"
"      border:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"      background-color: rgb(153, 178, 208);\n"
"}")
        self.controlsSettingsBtn_4.setIconSize(QSize(50, 50))
        self.Key_D_3 = QLabel(self.page_9)
        self.Key_D_3.setObjectName(u"Key_D_3")
        self.Key_D_3.setGeometry(QRect(390, 400, 141, 111))
        self.Key_D_3.setPixmap(QPixmap(u"Images/Icons/D.PNG"))
        self.Key_D_3.setScaledContents(True)
        self.label_29 = QLabel(self.page_9)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(270, 160, 731, 31))
        self.label_29.setFont(font12)
        self.label_29.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_30 = QLabel(self.page_9)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(320, 500, 121, 51))
        self.label_30.setFont(font5)
        self.label_30.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_31 = QLabel(self.page_9)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, 20, 71, 91))
        self.label_31.setPixmap(QPixmap(u"Images/Icons/trachmaniaIcon.jpg"))
        self.label_31.setScaledContents(True)
        self.controlsSettingsBtn_5 = QPushButton(self.page_9)
        self.controlsSettingsBtn_5.setObjectName(u"controlsSettingsBtn_5")
        self.controlsSettingsBtn_5.setGeometry(QRect(0, 120, 231, 71))
        self.controlsSettingsBtn_5.setFont(font3)
        self.controlsSettingsBtn_5.setCursor(QCursor(Qt.PointingHandCursor))
        self.controlsSettingsBtn_5.setStyleSheet(u"background-color: rgb(99, 122, 155);\n"
"color: rgb(255, 255, 255);\n"
"border:none;")
        self.controlsSettingsBtn_5.setIcon(icon4)
        self.controlsSettingsBtn_5.setIconSize(QSize(50, 50))
        self.label_33 = QLabel(self.page_9)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(90, 50, 131, 31))
        self.label_33.setFont(font11)
        self.label_33.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_34 = QLabel(self.page_9)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(280, 300, 141, 51))
        self.label_34.setFont(font5)
        self.label_34.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_35 = QLabel(self.page_9)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(270, 365, 151, 51))
        self.label_35.setFont(font5)
        self.label_35.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.Key_S_2 = QLabel(self.page_9)
        self.Key_S_2.setObjectName(u"Key_S_2")
        self.Key_S_2.setGeometry(QRect(390, 335, 141, 111))
        self.Key_S_2.setPixmap(QPixmap(u"Images/Icons/S.PNG"))
        self.Key_S_2.setScaledContents(True)
        self.Key_W_2 = QLabel(self.page_9)
        self.Key_W_2.setObjectName(u"Key_W_2")
        self.Key_W_2.setGeometry(QRect(390, 275, 141, 101))
        self.Key_W_2.setPixmap(QPixmap(u"Images/Icons/W.PNG"))
        self.Key_W_2.setScaledContents(True)
        self.logoutBtn_4 = QPushButton(self.page_9)
        self.logoutBtn_4.setObjectName(u"logoutBtn_4")
        self.logoutBtn_4.setGeometry(QRect(10, 660, 191, 51))
        self.logoutBtn_4.setFont(font3)
        self.logoutBtn_4.setCursor(QCursor(Qt.PointingHandCursor))
        self.logoutBtn_4.setLayoutDirection(Qt.LeftToRight)
        self.logoutBtn_4.setStyleSheet(u"QPushButton{\n"
"      color: rgb(255, 255, 255);\n"
"      border:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"      background-color: rgb(153, 178, 208);\n"
"}")
        self.logoutBtn_4.setIcon(icon2)
        self.logoutBtn_4.setIconSize(QSize(50, 55))
        self.stackedWidget.addWidget(self.page_9)
        self.page_8 = QWidget()
        self.page_8.setObjectName(u"page_8")
        self.label_13 = QLabel(self.page_8)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 20, 71, 91))
        self.label_13.setPixmap(QPixmap(u"Images/Icons/trachmaniaIcon.jpg"))
        self.label_13.setScaledContents(True)
        self.controlsSettingsBtn_2 = QPushButton(self.page_8)
        self.controlsSettingsBtn_2.setObjectName(u"controlsSettingsBtn_2")
        self.controlsSettingsBtn_2.setGeometry(QRect(0, 120, 231, 71))
        self.controlsSettingsBtn_2.setFont(font3)
        self.controlsSettingsBtn_2.setCursor(QCursor(Qt.PointingHandCursor))
        self.controlsSettingsBtn_2.setStyleSheet(u"background-color: rgb(99, 122, 155);\n"
"color: rgb(255, 255, 255);\n"
"border:none;")
        self.controlsSettingsBtn_2.setIcon(icon4)
        self.controlsSettingsBtn_2.setIconSize(QSize(50, 50))
        self.label_14 = QLabel(self.page_8)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(230, 0, 801, 111))
        self.label_14.setPixmap(QPixmap(u"Images/Backdrops/HeaderBackGround.png"))
        self.label_14.setScaledContents(True)
        self.label_15 = QLabel(self.page_8)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(0, 0, 231, 731))
        self.label_15.setPixmap(QPixmap(u"Images/Backdrops/SidePanel.png"))
        self.label_15.setScaledContents(True)
        self.logoutBtn_2 = QPushButton(self.page_8)
        self.logoutBtn_2.setObjectName(u"logoutBtn_2")
        self.logoutBtn_2.setGeometry(QRect(10, 660, 191, 51))
        self.logoutBtn_2.setFont(font3)
        self.logoutBtn_2.setCursor(QCursor(Qt.PointingHandCursor))
        self.logoutBtn_2.setLayoutDirection(Qt.LeftToRight)
        self.logoutBtn_2.setStyleSheet(u"QPushButton{\n"
"      color: rgb(255, 255, 255);\n"
"      border:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"      background-color: rgb(153, 178, 208);\n"
"}")
        self.logoutBtn_2.setIcon(icon2)
        self.logoutBtn_2.setIconSize(QSize(50, 55))
        self.launchGameBtn = QPushButton(self.page_8)
        self.launchGameBtn.setObjectName(u"launchGameBtn")
        self.launchGameBtn.setGeometry(QRect(830, 40, 171, 50))
        self.launchGameBtn.setFont(font13)
        self.launchGameBtn.setCursor(QCursor(Qt.PointingHandCursor))
        self.launchGameBtn.setStyleSheet(u"QPushButton {\n"
"    border-radius: 25px;\n"
"\n"
"      color: rgb(255, 255, 255);\n"
"\n"
"      background-color: rgb(122, 147, 183);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"      background-color: rgb(145, 176, 218);\n"
"}")
        self.launchGameBtn.setIcon(icon9)
        self.launchGameBtn.setIconSize(QSize(50, 50))
        self.label_17 = QLabel(self.page_8)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(90, 50, 131, 31))
        self.label_17.setFont(font11)
        self.label_17.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.controlsSettingsBtn_3 = QPushButton(self.page_8)
        self.controlsSettingsBtn_3.setObjectName(u"controlsSettingsBtn_3")
        self.controlsSettingsBtn_3.setGeometry(QRect(90, 80, 91, 31))
        self.controlsSettingsBtn_3.setFont(font14)
        self.controlsSettingsBtn_3.setCursor(QCursor(Qt.PointingHandCursor))
        self.controlsSettingsBtn_3.setStyleSheet(u"QPushButton{\n"
"      color: rgb(255, 255, 255);\n"
"      border:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"      background-color: rgb(153, 178, 208);\n"
"}")
        self.controlsSettingsBtn_3.setIconSize(QSize(50, 50))
        self.label_18 = QLabel(self.page_8)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(260, 130, 131, 21))
        self.label_18.setFont(font11)
        self.label_18.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_19 = QLabel(self.page_8)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(260, 260, 131, 21))
        self.label_19.setFont(font11)
        self.label_19.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.Key_A_2 = QLabel(self.page_8)
        self.Key_A_2.setObjectName(u"Key_A_2")
        self.Key_A_2.setGeometry(QRect(387, 330, 151, 111))
        self.Key_A_2.setPixmap(QPixmap(u"Images/Icons/A.PNG"))
        self.Key_A_2.setScaledContents(True)
        self.Key_D_2 = QLabel(self.page_8)
        self.Key_D_2.setObjectName(u"Key_D_2")
        self.Key_D_2.setGeometry(QRect(390, 260, 141, 111))
        self.Key_D_2.setPixmap(QPixmap(u"Images/Icons/D.PNG"))
        self.Key_D_2.setScaledContents(True)
        self.Key_P_2 = QLabel(self.page_8)
        self.Key_P_2.setObjectName(u"Key_P_2")
        self.Key_P_2.setGeometry(QRect(617, 325, 171, 121))
        self.Key_P_2.setPixmap(QPixmap(u"Images/Icons/P.png"))
        self.Key_P_2.setScaledContents(True)
        self.label_4 = QLabel(self.page_8)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(270, 160, 731, 31))
        self.label_4.setFont(font12)
        self.label_4.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_5 = QLabel(self.page_8)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(270, 180, 681, 41))
        self.label_5.setFont(font12)
        self.label_5.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_6 = QLabel(self.page_8)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(310, 290, 121, 51))
        self.label_6.setFont(font5)
        self.label_6.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_10 = QLabel(self.page_8)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(320, 360, 121, 51))
        self.label_10.setFont(font5)
        self.label_10.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_11 = QLabel(self.page_8)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(600, 360, 121, 51))
        self.label_11.setFont(font5)
        self.label_11.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_12 = QLabel(self.page_8)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(600, 290, 121, 51))
        self.label_12.setFont(font5)
        self.label_12.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.LightSpeedClip = QLabel(self.page_8)
        self.LightSpeedClip.setObjectName(u"LightSpeedClip")
        self.LightSpeedClip.setGeometry(QRect(290, 460, 141, 101))
        self.LightSpeedClip.setScaledContents(True)
        self.Key_W_3 = QLabel(self.page_8)
        self.Key_W_3.setObjectName(u"Key_W_3")
        self.Key_W_3.setGeometry(QRect(620, 255, 161, 121))
        self.Key_W_3.setPixmap(QPixmap(u"Images/Icons/W.PNG"))
        self.Key_W_3.setScaledContents(True)
        self.stackedWidget.addWidget(self.page_8)
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_13.raise_()
        self.controlsSettingsBtn_2.raise_()
        self.logoutBtn_2.raise_()
        self.launchGameBtn.raise_()
        self.label_17.raise_()
        self.controlsSettingsBtn_3.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.Key_A_2.raise_()
        self.Key_D_2.raise_()
        self.Key_P_2.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.LightSpeedClip.raise_()
        self.Key_W_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1022, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(1)
        self.stackedWidget_2.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"GesturePlay", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Welcome", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Ready to Start?", None))
        self.label_8.setText("")
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"to", None))
        self.Profile1.setText("")
        self.label_9.setText("")
        self.logoutBtn.setText(QCoreApplication.translate("MainWindow", u"Main Screen", None))
        self.cameraSettingsBtn.setText(QCoreApplication.translate("MainWindow", u" Camera Settings", None))
        self.controlsSettingsBtn.setText(QCoreApplication.translate("MainWindow", u"   Controls Settings", None))
        self.gameSelectionBtn.setText(QCoreApplication.translate("MainWindow", u"Game Selection", None))
        self.label.setText("")
        self.label_38.setText("")
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"Game Selection", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"Please Select a game", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"Light Speed", None))
        self.lightSpeedBtn.setText("")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Search for a game", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"Tank Game", None))
        self.tankGameBtn.setText("")
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"Profile Settings", None))
        self.Profile1_3.setText("")
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"Profile1", None))
        self.editProfileBtn_2.setText("")
        self.label_45.setText("")
        self.removeProfileBtn_4.setText(QCoreApplication.translate("MainWindow", u"Save Changes", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Webcam", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"Camera Settings", None))
        self.CameraSelection.setPlaceholderText(QCoreApplication.translate("MainWindow", u"System Default", None))
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"Capture Webcam", None))
        self.label_47.setText("")
        self.CameraPreview.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_32.setText("")
        self.label_50.setText(QCoreApplication.translate("MainWindow", u"Controls Settings", None))
        self.Key_A.setText("")
        self.Key_D.setText("")
        self.Key_S.setText("")
        self.Key_W.setText("")
        self.imgLabel1.setText("")
        self.imgLabel2.setText("")
        self.imgLabel3.setText("")
        self.imgLabel4.setText("")
        self.Key_G.setText("")
        self.imgLabel5.setText("")
        self.Key_I.setText("")
        self.Key_O.setText("")
        self.Key_P.setText("")
        self.Key_U.setText("")
        self.imgLabel6.setText("")
        self.imgLabel7.setText("")
        self.imgLabel8.setText("")
        self.imgLabel9.setText("")
        self.label_36.setText("")
        self.label_37.setText("")
        self.label_49.setText("")
        self.label_51.setText("")
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Description", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"action-packed game.", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Pause:", None))
        self.label_22.setText("")
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Light Speed", None))
        self.logoutBtn_3.setText(QCoreApplication.translate("MainWindow", u"Main Screen", None))
        self.launchGameBtn_2.setText(QCoreApplication.translate("MainWindow", u"Launch Game", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Shoot:", None))
        self.LightSpeedClip_2.setText("")
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Move Right:", None))
        self.Key_G_3.setText("")
        self.Key_P_3.setText("")
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Controls", None))
        self.label_28.setText("")
        self.Key_A_3.setText("")
        self.controlsSettingsBtn_4.setText(QCoreApplication.translate("MainWindow", u"Change Game", None))
        self.Key_D_3.setText("")
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Take command of a powerful tank and engage in thrilling battles against AI-controlled enemy tanks in this", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Move Left:", None))
        self.label_31.setText("")
        self.controlsSettingsBtn_5.setText(QCoreApplication.translate("MainWindow", u"   Game Description", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"Tank Game", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"Move Forward:", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"Move Backward:", None))
        self.Key_S_2.setText("")
        self.Key_W_2.setText("")
        self.logoutBtn_4.setText(QCoreApplication.translate("MainWindow", u"Main Screen", None))
        self.label_13.setText("")
        self.controlsSettingsBtn_2.setText(QCoreApplication.translate("MainWindow", u"   Game Description", None))
        self.label_14.setText("")
        self.label_15.setText("")
        self.logoutBtn_2.setText(QCoreApplication.translate("MainWindow", u"Main Screen", None))
        self.launchGameBtn.setText(QCoreApplication.translate("MainWindow", u"Launch Game", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Light Speed", None))
        self.controlsSettingsBtn_3.setText(QCoreApplication.translate("MainWindow", u"Change Game", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Description", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Controls", None))
        self.Key_A_2.setText("")
        self.Key_D_2.setText("")
        self.Key_P_2.setText("")
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Light Speed is a dynamic 2D platformer where you control a spirited ball on a thrilling journey through", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"challenging landscapes. Navigate through obstacles and dodge traps as you make your way to victory!", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Move Right:", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Move Left:", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Pause:", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Jump:", None))
        self.LightSpeedClip.setText("")
        self.Key_W_3.setText("")
    # retranslateUi

